# Generated by Django 4.2.4 on 2023-09-19 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='CarwashRequestCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '89999999999' или '+79999999999'", regex='^\\+?1?\\d{9,12}$')], verbose_name='номер телефона')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'Request Call',
                'verbose_name_plural': 'Request Call',
            },
        ),
        migrations.CreateModel(
            name='CarWashService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='название')),
                ('process_time', models.SmallIntegerField(default=0, verbose_name='длительность')),
                ('price_standart', models.IntegerField(default=0, verbose_name='седан, хетчбэк')),
                ('price_crossover', models.IntegerField(default=0, verbose_name='кроссовер')),
                ('price_offroad', models.IntegerField(default=0, verbose_name='внедорожник')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CarWashUserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reg', models.DateField(verbose_name='дата регистрации')),
                ('time_reg', models.TimeField(verbose_name='время регистрации')),
            ],
            options={
                'verbose_name': 'Запись пользователя',
                'verbose_name_plural': 'Записи пользователей',
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='дата')),
                ('time_1000', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example1', to='carwash.carwashregistration')),
                ('time_1030', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example2', to='carwash.carwashregistration')),
                ('time_1100', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example3', to='carwash.carwashregistration')),
                ('time_1130', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example4', to='carwash.carwashregistration')),
                ('time_1200', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example5', to='carwash.carwashregistration')),
                ('time_1230', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example6', to='carwash.carwashregistration')),
                ('time_1300', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example7', to='carwash.carwashregistration')),
                ('time_1330', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example8', to='carwash.carwashregistration')),
                ('time_1400', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example9', to='carwash.carwashregistration')),
                ('time_1430', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example10', to='carwash.carwashregistration')),
                ('time_1500', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example11', to='carwash.carwashregistration')),
                ('time_1530', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example12', to='carwash.carwashregistration')),
                ('time_1600', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example13', to='carwash.carwashregistration')),
                ('time_1630', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example14', to='carwash.carwashregistration')),
                ('time_1700', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example15', to='carwash.carwashregistration')),
                ('time_1730', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example16', to='carwash.carwashregistration')),
                ('time_1800', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example17', to='carwash.carwashregistration')),
                ('time_1830', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example18', to='carwash.carwashregistration')),
                ('time_1900', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example19', to='carwash.carwashregistration')),
                ('time_1930', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example20', to='carwash.carwashregistration')),
                ('time_2000', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example21', to='carwash.carwashregistration')),
                ('time_2030', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example22', to='carwash.carwashregistration')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дни',
            },
        ),
    ]
