# Generated by Django 4.2.7 on 2023-11-16 20:37

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reg', models.DateField(verbose_name='дата записи')),
                ('time_reg', models.TimeField(verbose_name='время записи')),
                ('total_time', models.PositiveSmallIntegerField(default=0, verbose_name='общее время работ')),
                ('relation_carwashworkday', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='CarWashRequestCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: "89999999999"', regex='8\\d{10}$')], verbose_name='номер телефона')),
                ('processed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'Request Call',
                'verbose_name_plural': 'Request Call',
            },
        ),
        migrations.CreateModel(
            name='CarWashService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('process_time', models.PositiveSmallIntegerField(default=0, verbose_name='длительность')),
                ('price_standart', models.PositiveIntegerField(default=0, verbose_name='седан, хетчбэк')),
                ('price_crossover', models.PositiveIntegerField(default=0, verbose_name='кроссовер')),
                ('price_offroad', models.PositiveIntegerField(default=0, verbose_name='внедорожник')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CarWashWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique_for_date=True, verbose_name='дата')),
                ('time_1000', models.JSONField(blank=True, default=None, null=True)),
                ('time_1030', models.JSONField(blank=True, default=None, null=True)),
                ('time_1100', models.JSONField(blank=True, default=None, null=True)),
                ('time_1130', models.JSONField(blank=True, default=None, null=True)),
                ('time_1200', models.JSONField(blank=True, default=None, null=True)),
                ('time_1230', models.JSONField(blank=True, default=None, null=True)),
                ('time_1300', models.JSONField(blank=True, default=None, null=True)),
                ('time_1330', models.JSONField(blank=True, default=None, null=True)),
                ('time_1400', models.JSONField(blank=True, default=None, null=True)),
                ('time_1430', models.JSONField(blank=True, default=None, null=True)),
                ('time_1500', models.JSONField(blank=True, default=None, null=True)),
                ('time_1530', models.JSONField(blank=True, default=None, null=True)),
                ('time_1600', models.JSONField(blank=True, default=None, null=True)),
                ('time_1630', models.JSONField(blank=True, default=None, null=True)),
                ('time_1700', models.JSONField(blank=True, default=None, null=True)),
                ('time_1730', models.JSONField(blank=True, default=None, null=True)),
                ('time_1800', models.JSONField(blank=True, default=None, null=True)),
                ('time_1830', models.JSONField(blank=True, default=None, null=True)),
                ('time_1900', models.JSONField(blank=True, default=None, null=True)),
                ('time_1930', models.JSONField(blank=True, default=None, null=True)),
                ('time_2000', models.JSONField(blank=True, default=None, null=True)),
                ('time_2030', models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дни',
            },
        ),
    ]
