# Generated by Django 4.2.4 on 2023-09-20 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashrequestcall',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '89999999999'", regex='8\\d{10}$')], verbose_name='номер телефона'),
        ),
    ]
