# Generated by Django 4.2.7 on 2023-11-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashregistration',
            name='total_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='общяя стоимость'),
        ),
    ]
