# Generated by Django 4.2.6 on 2023-10-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashregistration',
            name='total_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='суммарное время работ'),
        ),
    ]
