# Generated by Django 4.2.6 on 2023-10-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_carwashregistration_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashregistration',
            name='total_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='общее время работ'),
        ),
        migrations.AlterField(
            model_name='carwashservice',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(unique=True, verbose_name='дата'),
        ),
    ]
