# Generated by Django 4.2.4 on 2023-09-18 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_carwashcallme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carwashcallme',
            options={'verbose_name': 'Call Me', 'verbose_name_plural': 'Call Me'},
        ),
        migrations.AlterField(
            model_name='carwashcallme',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '89999999999 или +79999999999'", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
