# Generated by Django 4.2.4 on 2023-09-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_alter_carwashrequestcall_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashrequestcall',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
