# Generated by Django 4.2.4 on 2023-09-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_alter_workday_date_carwashuserregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carwashuserregistration',
            old_name='data_time',
            new_name='date_time',
        ),
    ]
