# Generated by Django 4.2.4 on 2023-09-28 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0004_carwashrequestcall_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashrequestcall',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='carwashrequestcall',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '89999999999'", regex='8\\d{10}$')], verbose_name='номер телефона'),
        ),
    ]
