# Generated by Django 4.2.4 on 2023-09-18 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0004_alter_carwashcallme_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashcallme',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='carwashcallme',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '89999999999' или '+79999999999'", regex='^\\+?1?\\d{9,12}$')], verbose_name='номер телефона'),
        ),
    ]
