# Generated by Django 4.2.7 on 2023-11-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0004_alter_carwashworkday_time_1000_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashworkday',
            name='date',
            field=models.DateField(unique=True, verbose_name='дата'),
        ),
    ]
