# Generated by Django 4.2.7 on 2023-11-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0004_alter_carwashregistration_total_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(unique_for_date=True, verbose_name='дата'),
        ),
    ]
