# Generated by Django 4.2.4 on 2023-09-29 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0006_alter_carwashrequestcall_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashrequestcall',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан'),
        ),
    ]
