# Generated by Django 4.2.4 on 2023-10-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0008_alter_workday_time_1000_alter_workday_time_1030_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashuserregistration',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carwash.carwashregistration'),
        ),
    ]
